#include "render_mesh.c"
#include "render_camera.c"
#include "render_scene.c"
#include "render_clear.c"
#include "render_graph_types.c"
#include "render_pool.c"
#include "render_pass.c"
#include "render_tracker.c"
#include "render_graph.c"

#include "probe/render_probe_inc.c"
#include "ssao/render_ssao_inc.c"
#include "volumetric/render_volumetric_inc.c"

#include "debug/render_debug_inc.c"
#include "pass/render_pass_inc.c"
